config/routes.rb
Rails.application.routes.draw do
  root 'search#index'

  resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<div class="de-header">
  <div class="de-header2">
    <%= link_to 'mikke', '/', class: "de-header_title" %>
  </div>
  <div class="de-header3">
    <div class="de-header3-search">
      <div class="de-header3-search2">
        <%= form_tag(search_index_path(), method: :get, enforce_utf8: false) do %>
          <%= text_field_tag :keyword, "", class: 'input-keyword', placeholder: "キーワードで検索  ex. 日本酒・英会話", required: :true %>
          <%= submit_tag '探す', class: 'search-btn', name: nil %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mikke1.0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/search/index.html.erb
<div>
  <%= render partial: 'layouts/header', local: { header: @header } %>
</div>
<div class="wrapper">
  <div class="main">
    <div class="main-top">
      <div class="main-message">
        <span>mikkeとは</span><br>
        mikkeは、キーワードを入力するだけでお気に入りのTwitterアカウントが見つかるサイトです。</br>
        今や主要メディアは「個」の時代です。有益な情報を集める手段として、</br>
        Twitterアカウントをフォローしてみてはいかがでしょうか？
      </div>
    </div>
  </div>
</div>